# Generated by Django 2.2.3 on 2019-07-13 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(default=None, max_length=120)),
                ('message', models.TextField(default=None, max_length=99)),
            ],
        ),
        migrations.CreateModel(
            name='user_message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(default=None, max_length=120)),
                ('message', models.TextField(default=None, max_length=99)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='user_app.ChatUser')),
            ],
        ),
    ]
