# Generated by Django 2.2.3 on 2019-07-14 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20190714_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_app.ChatUser'),
        ),
    ]
