# Generated by Django 2.2.3 on 2019-07-14 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20190714_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['time']},
        ),
        migrations.AlterModelOptions(
            name='user_message',
            options={'ordering': ['time']},
        ),
    ]
